"""Reusable extension helpers for user-provided analysis code."""

from lamet_agent.extensions.plot_presets import (
    AXIS_FONT,
    COLOR_CYCLE,
    COMMON_LABELS,
    ERRORBAR_CIRCLE_STYLE,
    ERRORBAR_STYLE,
    FIGURE_SIZE,
    MARKER_CYCLE,
    SMALL_AXIS_FONT,
    TICK_STYLE,
    apply_publication_style,
    auto_ylim,
    default_plot,
    default_sub_plot,
)
from lamet_agent.extensions.statistics import (
    bin_data,
    bootstrap,
    bootstrap_average,
    bootstrap_average_no_correlation,
    constant_fit,
    gvar_dict_to_correlated_samples,
    gvar_list_to_correlated_samples,
    jackknife,
    jackknife_average,
    save_gvar_dict_samples_to_h5,
)
from lamet_agent.extensions.two_point import (
    DEFAULT_BOOTSTRAP_SAMPLES,
    EffectiveMassResult,
    ResampledCorrelator,
    build_two_point_priors,
    effective_mass_from_correlator,
    extract_state_energies,
    fit_two_point_correlator,
    resample_two_point_correlator,
    summarize_two_point_fit,
    two_point_fit_function,
)

__all__ = [
    "AXIS_FONT",
    "COLOR_CYCLE",
    "COMMON_LABELS",
    "ERRORBAR_CIRCLE_STYLE",
    "ERRORBAR_STYLE",
    "FIGURE_SIZE",
    "MARKER_CYCLE",
    "SMALL_AXIS_FONT",
    "TICK_STYLE",
    "apply_publication_style",
    "auto_ylim",
    "default_plot",
    "default_sub_plot",
    "bin_data",
    "bootstrap",
    "bootstrap_average",
    "bootstrap_average_no_correlation",
    "constant_fit",
    "gvar_dict_to_correlated_samples",
    "gvar_list_to_correlated_samples",
    "jackknife",
    "jackknife_average",
    "save_gvar_dict_samples_to_h5",
    "DEFAULT_BOOTSTRAP_SAMPLES",
    "EffectiveMassResult",
    "ResampledCorrelator",
    "build_two_point_priors",
    "effective_mass_from_correlator",
    "extract_state_energies",
    "fit_two_point_correlator",
    "resample_two_point_correlator",
    "summarize_two_point_fit",
    "two_point_fit_function",
]
