"""Artifact models used for stage outputs and final reports."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np


def _to_json_safe(value: Any) -> Any:
    """Convert nested NumPy-heavy payloads into JSON-safe data."""
    if isinstance(value, dict):
        return {key: _to_json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_to_json_safe(item) for item in value]
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.ndarray):
        return [_to_json_safe(item) for item in value.tolist()]
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, complex):
        return {"real": value.real, "imag": value.imag}
    return value


@dataclass(slots=True)
class ArtifactRecord:
    """Describes a single output generated by a workflow stage."""

    name: str
    kind: str
    path: Path
    description: str
    format: str

    def to_dict(self) -> dict[str, Any]:
        """Serialize the artifact for JSON reports."""
        return {
            "name": self.name,
            "kind": self.kind,
            "path": str(self.path),
            "description": self.description,
            "format": self.format,
        }


@dataclass(slots=True)
class StageResult:
    """Normalized result returned by every stage implementation."""

    stage_name: str
    summary: str
    payload: dict[str, Any] = field(default_factory=dict)
    artifacts: list[ArtifactRecord] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Serialize the stage result for reports."""
        return {
            "stage_name": self.stage_name,
            "summary": self.summary,
            "payload": _to_json_safe(self.payload),
            "artifacts": [artifact.to_dict() for artifact in self.artifacts],
        }
